### ISSUE TITLE
Minor correction of original schematics.

### ISSUE THREAD

**Issue by henri62** [happymacer/PF906-treadmill-motor-controller-#1]
FYI: (since the original kicad schematic is not published I cannot modify it myself)

Please adjust the schematic:
R26 =390k (and is often the cause of a defect with code E1)
C6 is a non-polar ceramic capactor of 10 n/ 1kV.
R9 = 560 k

J3-pin1 is also connected to J5-pin2, add a label at the left bottom somewhere too.

**Comment by happymacer** [comment]
Thanks for the input Henri62.  I have corrected the schematic as follows:
R26 updated to 390k
C6 on my board is 2kV, and as its the "conservative" alternative Ive left it as is.  Added Ceramic and changed symbol to non polarised
R9 is already set at 560k - not sure what you meant.
J3-1 link to J5-2 is already shown on sheet 7 so not added to sheet 1.

I will upload the new schematic file shortly.

**Comment by henri62** [comment]
Both R9 and C6 had no value in the schematic. But I see now that the schematic is completely updated into multiple pages and much more detailed.
The schematic I saw (and where the comment was based on) was only 1 page. That is where the confusion comes from.
This issue can be closed.

**Comment by happymacer** [comment]
ta, no worries!
