### ISSUE TITLE
Relay part number 

### ISSUE THREAD

**Issue by kambadur** [happymacer/PF906-treadmill-motor-controller-#2]
Appreciate the good work. Have you identified the ac supply side relay part number? If so could you please sahre it.
If not, do you know any same form factor relay for replacement?
Thank you and kind regards,
Sam

**Comment by kambadur** [comment]
On the similar type of controller DK12-A01A, the relay part number is identified to be
HSINDA 942H-1A-12DS

**Comment by happymacer** [comment]
Thanks Kambadur! Nice to hear!  The supply side relay is a HSINDA953-1A-12DG-1.  Im sure there are many similar relays out there.

**Comment by kambadur** [comment]
Thank you too. Couldn't find the exact part. Got a near one `G2RL-1A-E 12DC`. Also from testing found out today that the power stage IGBT was also broken. Ordered the part as well `STGW20NC60VD`
Your work helped a lot with debugging. Thanks again.
